---
# tasks file for jono_zsh

- name: Install Zsh
  ansible.builtin.package:
    name: zsh
  become: true

- name: Install chsh
  ansible.builtin.package:
    name: util-linux-user
  become: true
  when: '"Rocky" in ansible_distribution'

- name: Install Git
  ansible.builtin.package:
    name: git
  become: true

- name: Check if OhMyZsh exists
  ansible.builtin.stat:
    path: '{{ path_omz }}'
  register: ohmyzsh_check

- name: Pull OhMyZsh Repo
  ansible.builtin.shell: /bin/sh -c "$(curl -fsSL '{{ omz_install }}')" "" --unattended
  changed_when: false
  when: not ohmyzsh_check.stat.exists

- name: Git Pull PowerLevel10k
  ansible.builtin.git:
    repo: '{{ pl10k_src }}'
    dest: '{{ pl10k_dest }}'
    single_branch: true

- name: Copy PowerLevel10k Config
  ansible.builtin.copy:
    src: '{{ pl10k_conf }}'
    dest: '{{ path_top }}'

- name: Copy Zsh Config
  ansible.builtin.copy:
    src: '{{ zshrc }}'
    dest: '{{ path_top }}'

- name: Make Zsh default
  ansible.builtin.user:
    name: '{{ user }}'
    shell: /bin/zsh
  become: true
  when: root_required
